name: Enviar Mensaje a Discord

on:
  schedule:
    - cron: '0 9 * * *'  # Ejecutar todos los días a las 9:00 AM UTC (ajusta según tu zona horaria)

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Reemplaza con la versión de Python que estés utilizando

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Instala la biblioteca 'requests' necesaria para enviar solicitudes HTTP

      - name: Ejecutar script de Python
        run: |
          python send_message.py  # Ajusta el nombre del script según tu configuración
